// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://igpqxkktzelrzkyelpfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncHF4a2t0emVscnpreWVscGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDkwNzMsImV4cCI6MjA2MDIyNTA3M30.q_2-tMNQsXrNQyutUr2AqY8zhSoYaYw7m-lbLogohZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
